
apiVersion: v1
kind: ReplicationController
metadata:
  name: kafka-1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kafka
        server-id: "1"
    spec:
      volumes:
        - name: data
          gcePersistentDisk:
            pdName: kafka-1
            fsType: ext4
      containers:
        - name: server
          image: wurstmeister/kafka:latest
          env:
            - name: KAFKA_LOG_DIRS
              value: /kafka
            - name: KAFKA_ADVERTISED_HOST_NAME
              value: 192.168.99.100
            - name: KAFKA_ADVERTISED_PORT
              value: "9092"
            - name: KAFKA_LOG_RETENTION_HOURS
              value: "168"
            - name: KAFKA_LOG_RETENTION_BYTES
              value: "100000000"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: zookeeper-1:2181,zookeeper-2:2181,zookeeper-3:2181
          ports:
            - containerPort: 9092
          volumeMounts:
            - mountPath: /kafka
              name: data
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: kafka-2
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kafka
        server-id: "2"
    spec:
      volumes:
        - name: data
          gcePersistentDisk:
            pdName: kafka-2
            fsType: ext4
      containers:
        - name: server
          image: wurstmeister/kafka:latest
          env:
            - name: KAFKA_LOG_DIRS
              value: /kafka
            - name: KAFKA_ADVERTISED_HOST_NAME
              value: 192.168.99.100
            - name: KAFKA_ADVERTISED_PORT
              value: "9093"
            - name: KAFKA_LOG_RETENTION_HOURS
              value: "168"
            - name: KAFKA_LOG_RETENTION_BYTES
              value: "100000000"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: zookeeper-1:2181,zookeeper-2:2181,zookeeper-3:2181
          ports:
            - containerPort: 9092
          volumeMounts:
            - mountPath: /kafka
              name: data
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: kafka-3
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kafka
        server-id: "3"
    spec:
      volumes:
        - name: data
          gcePersistentDisk:
            pdName: kafka-3
            fsType: ext4
      containers:
        - name: server
          image: wurstmeister/kafka:latest
          env:
            - name: KAFKA_LOG_DIRS
              value: /kafka
            - name: KAFKA_CREATE_TOPICS
              value: test-topic-1:1:2,test-topic-2:1:2,test-topic-3:1:2
            - name: KAFKA_ADVERTISED_HOST_NAME
              value: 192.168.99.100
            - name: KAFKA_ADVERTISED_PORT
              value: "9094"
            - name: KAFKA_LOG_RETENTION_HOURS
              value: "168"
            - name: KAFKA_LOG_RETENTION_BYTES
              value: "100000000"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: zookeeper-1:2181,zookeeper-2:2181,zookeeper-3:2181
          ports:
            - containerPort: 9092
          volumeMounts:
            - mountPath: /kafka
              name: data
